
samples: config/samples.tsv

genome:
  fasta: /gpfs3/well/davies/users/xxd908/pipelines/animal/sheep/data/fasta/Ovis_aries.Oar_v3.1.dna.toplevel.fa
  species: sheep
  build: Oar_v3.1
  refpanel: config/refpanel.tsv

downsample: [0.1, 0.25, 0.5, 1.0, 2.0]

# refsize: [0, 100, 200, 300, 400]
refsize: [0]

chroms: ['21']

scenario: 'speed' #'all', 'speed', 'accuracy', 'quilt', 'glimpse'

quilt:
  chunksize: 2000000
  nGen: 20
  buffer: 500000
  Ksubset: 400
  nGibbsSamples: 7
  n_seek_its: 3
  n_burn_in_seek_its: NA
  small_ref_panel_gibbs_iterations: "c(3,6,9)"
  small_ref_panel_gibbs_iterations: 20
  pbwtL: 2
  pbwtS: 8

glimpse:
  chunksize: 2000000
  buffer: 500000
  bq: 20
  mq: 20
  burnin: 10
  main: 15
  pbwt-depth: 2
  pbwt-modulo: 8
  ne: 20000
