
samples: config/samples.tsv

genome:
  fasta: data/human/GRCh38_full_analysis_set_plus_decoy_hla.fa
  species: human
  build: GRCh38
  refpanel: config/refpanel.tsv

downsample: [0.1, 1.0]

# refsize: [0, 100, 200, 300, 400]
refsize: [0]

chroms: ['chr20']

#'all', 'speed', 'accuracy', 'quilt1', 'glimpse1', 'quilt2', 'glimpse2'
scenario: 'all'

quilt2:
  chunksize: 2000000
  nGen: 100
  buffer: 500000
  Ksubset: 1000
  nGibbsSamples: 7
  n_seek_its: 5
  n_burn_in_seek_its: 2
  small_ref_panel_block_gibbs_iterations: c(3,6,9)
  small_ref_panel_gibbs_iterations: 20
  lowram: 'TRUE'
  impute_rare_common: 'FALSE'
  mspbwtB: 64
  mspbwtL: 40
  mspbwtM: 1
  mspbwt-nindices: 4
  mspbwtMAF: 0.0

quilt1:
  chunksize: 2000000
  nGen: 100
  buffer: 500000
  Ksubset: 400
  nGibbsSamples: 7
  n_seek_its: 3
  n_burn_in_seek_its: 2
  small_ref_panel_block_gibbs_iterations: c(3,6,9)
  small_ref_panel_gibbs_iterations: 20
  lowram: 'TRUE'
  impute_rare_common: 'FALSE'

glimpse:
  chunksize: 2000000
  buffer: 500000
  bq: 20
  mq: 20
  burnin: 10
  main: 10
  pbwt-depth: 2
  pbwt-modulo: 8
  ne: 20000


# global programs
time: "/usr/bin/time"
