
samples: config/samples.tsv

genome:
  fasta: data/human/GRCh38_full_analysis_set_plus_decoy_hla.fa
  species: human
  build: GRCh38
  refpanel: config/refpanel.tsv

downsample: [0.1, 1.0]

# refsize: [0, 100, 200, 300, 400]
refsize: [0]

chroms: ['chr20']

#'all', 'speed', 'accuracy', 'quilt','glimpse','quilt1', 'quilt2', 'glimpse1',  'glimpse2'
scenario: 'all'

## we wanna output some extra variants in buffer for ligation
extra_buffer_in_quilt: 100000
chunksize: 5000000

quilt2:
  chunksize: 2000000
  nGen: 100
  buffer: 400000
  nGibbsSamples: 7
  small_ref_panel_block_gibbs_iterations: c(3,6,9)
  small_ref_panel_gibbs_iterations: 20
  lowram: 'TRUE'
  Ksubset: 400
  n_seek_its: 3
  impute_rare_common: 'TRUE'
  mspbwtB: 64
  mspbwtL: 40
  mspbwtM: 3
  mspbwt-nindices: 4
  rare_af_threshold: 0.001

quilt1:
  chunksize: 2000000
  nGen: 100
  buffer: 400000
  nGibbsSamples: 7
  small_ref_panel_block_gibbs_iterations: c(3,6,9)
  small_ref_panel_gibbs_iterations: 20
  lowram: 'TRUE'
  Ksubset: 400
  n_seek_its: 3
  impute_rare_common: 'TRUE'
  rare_af_threshold: 0.001

glimpse2:
  chunksize: 2000000
  buffer: 500000
  bq: 20
  mq: 20
  burnin: 5
  main: 15
  pbwt-depth: 12
  pbwt-modulo-cm: 0.1
  ne: 100000


glimpse1:
  chunksize: 2000000
  buffer: 500000
  bq: 20
  mq: 20
  burnin: 10
  main: 10
  pbwt-depth: 2
  pbwt-modulo: 8
  ne: 20000

# global programs
time: "/usr/bin/time"
